# Generated by Django 5.0.3 on 2024-04-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_href', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('source_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Web3event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('image', models.CharField()),
                ('organizers', models.CharField()),
                ('address', models.CharField()),
                ('time', models.CharField()),
                ('description', models.CharField()),
                ('presenter', models.CharField()),
                ('tags', models.CharField()),
            ],
        ),
    ]
